### ISSUE TITLE
No module named cv2 / numpy

### ISSUE THREAD

**Issue by neelmitra** [awslabs/aws-iot-greengrass-accelerators#1]
HI,

I am running the workshop in ubuntu . 

When i try to deploy the gg group, the deployment fails with the following error - 

```
Deployment 91759824-87b6-4885-b979-6309cbba1d5f of type NewDeployment for group ae011966-24b7-4696-9add-ce32a5db0aa9 failed error: worker with a7172fb7-926b-41b2-63d6-3ae529cc6e2b failed to initialize
```

 i get the below errors in the respective logs - 

**In GG-ML-INF-image-classification-image-classification.log -**

```
[[2020-04-13T02:26:50.679Z][FATAL]-lambda_runtime.py:140,Failed to import handler function "handlers.handler" due to exception: No module named 'cv2'](url)
```

I installed opencv (sudo apt-get install python-opencv) but it didnot work. 

**In MLFeedback.log -**

```
[2020-04-13T02:26:48.578Z][INFO]-ipc_client.py:192,Getting work for function [arn:aws:lambda:us-east-1:aws:function:MLFeedback:1] from http://localhost:8000/2016-11-01/functions/arn:aws:lambda:us-east-1:aws:function:MLFeedback:1/work
[2020-04-13T02:26:50.3Z][INFO]-lambda_runtime.py:364,Caught signal 15. Stopping runtime.
```

**In pinned-accelerator-e2e.log -** 

```
[2020-04-13T02:26:50.043Z][FATAL]-lambda_runtime.py:140,Failed to import handler function "mlconnector.handler" due to exception: No module named 'numpy'
[2020-04-13T02:26:50.496Z][FATAL]-lambda_runtime.py:380,Failed to initialize Lambda runtime due to exception: No module named 'numpy'
```
**Greengrass runtime log -** 

[2020-04-13T02:26:51.694Z][INFO]-Worker Memory Usage (KB).      {"workerId": "a7172fb7-926b-41b2-63d6-3ae529cc6e2b", "funcArn": "arn:aws:lambda:us-east-1:aws:function:GG-ML-INF-image-classification-image-classification:2", "memSize": 512000, "memUsed": 24484}
[2020-04-13T02:26:51.694Z][ERROR]-Worker is ungracefully killed.        {"workerId": "a7172fb7-926b-41b2-63d6-3ae529cc6e2b", "funcArn": "arn:aws:lambda:us-east-1:aws:function:GG-ML-INF-image-classification-image-classification:2", "state": "exit status 1"}
[2020-04-13T02:26:51.695Z][ERROR]-Failed to restart pinned lambda.      {"workerId": "a7172fb7-926b-41b2-63d6-3ae529cc6e2b", "funcArn": "arn:aws:lambda:us-east-1:aws:function:GG-ML-INF-image-classification-image-classification:2", "errorString": "worker manager is not allowing new workers: cannot restart worker arn:aws:lambda:us-east-1:aws:function:GG-ML-INF-image-classification-image-classification:2[a7172fb7-926b-41b2-63d6-3ae529cc6e2b]"}
[2020-04-13T02:26:51.695Z][ERROR]-Failed to restart pinned lambda.      {"workerId": "a7172fb7-926b-41b2-63d6-3ae529cc6e2b", "funcArn": "arn:aws:lambda:us-east-1:aws:function:GG-ML-INF-image-classification-image-classification:2", "errorString": "worker initialization error: worker with a7172fb7-926b-41b2-63d6-3ae529cc6e2b failed to initialize"}

**Comment by kangks** [comment]
If I am not mistaken, `sudo apt-get install python-opencv` installs in the Python2.x libraries. However, the connector needs [Python3.7 runtime](https://github.com/awslabs/aws-iot-greengrass-accelerators/blob/67dcc04efaf08ad897bcb0e44ea26cf997980d40/accelerators/machine_learning_inference/cfn/mli_accelerator-connector-INPUT.cfn.yaml#L107).

Could you try install open-cv in Python3.7 instead with this command `python3.7 -m pip install opencv-python`?

**Comment by neelmitra** [comment]
I tried this but getting the below error. Tried to reinstall python and other solutions in google , not working yet. 

root@ip-172-31-75-91:~# python3.7 -m pip install opencv-python
Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/dist-packages
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/dist-packages (from opencv-python)
root@ip-172-31-75-91:~# 
root@ip-172-31-75-91:~# python3.7 -c 'import cv2; print(cv2.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

**Comment by neelmitra** [comment]
The issue is resolved with the following - 

apt install python3.7 python3-pip -y
apt-get install -y libsm6 libxext6 libxrender-dev libglib2.0-0 libgfortran3
python3.7 -m pip install opencv-python

**Comment by kangks** [comment]
Thanks @neelmitra for pointing this out - I have submitted a [PR](https://github.com/awslabs/aws-iot-greengrass-accelerators/pull/2) to include AWS Greengrass developer guide that can help reduce friction to this issue.

**Comment by gadams999** [comment]
Closing, commit merged to master branch

**Comment by matheuscanela** [comment]
Hi @neelmitra  and @kangks 

I am getting the same error. Could you help me?

I tried to update python2 and python3, but it is still getting the error 

lambda_runtime.py:140,Failed to import handler function "handlers.handler" due to exception: No module named 'cv2'

**Comment by jaimedantas** [comment]
The only thing that worked for me was:
`sudo -H -u ggc_user python3 -m pip install your_module`
